### ISSUE TITLE
loading screen while save operations happen

### ISSUE THREAD

**Issue by jrmcdona** [guns2410/redux-storage#1]
Hello-

I am trying to figure out how to know when all of my Save operations have completed, so I can move to the next screen.

Right now we have about 5 save operations on start up.  

Best practice for knowing when those have completed?

Thanks!

**Comment by guns2410** [comment]
you could use `load(store)` to achieve this

```javascript
load(store)
    .then((newState) => this.setState({ loading: false })) // set your state or flag here
    .catch(() => console.log('Failed to load previous state'));
```

usually this could be in componentDidMount
