### ISSUE TITLE
Please push an update to NPM

### ISSUE THREAD

**Issue by NathanielHill** [guns2410/redux-storage#15]
There hasn't been a release in two years, and there have been some bug fixes now. Can we bump a release out to npm?

**Comment by NathanielHill** [comment]
Is there a problem with publishing? Do you have the npm keys to publish an update @guns2410?

I'm tired of getting peer dep warnings constantly. Can we publish an update please

**Comment by NathanielHill** [comment]
I'm happy to do the publish, I just don't know the npm key situation.

Have there been any breaking changes since v`4.1.2`? @guns2410

**Comment by NathanielHill** [comment]
Looks like the only change besides some documentation updates is:

1) Updating peer deps to include redux 4
2) The ability to skip dispatching save actions

Would it be safe to push a release as `4.2.0`?

**Comment by alexey-pelykh** [comment]
Please do the release :)

**Comment by alexey-pelykh** [comment]
It's also related to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34791

**Comment by duydao** [comment]
@NathanielHill Is someone maintaining this repo or is there a fork?

**Comment by NathanielHill** [comment]
@duydao As far as I know, @guns2410 is the only one with permissions, and hasn't been active since Jan 17th.

I would push an update but I don't have the NPM keys.

**Comment by paztis** [comment]
I'm tired of waiting a release.
I've fork here https://github.com/paztis/redux-storage, rename it to **@paztis/redux-storage** and publish version 4.2.0 here https://www.npmjs.com/package/@paztis/redux-storage

You can take it from npm if you want

**Comment by renanbandeira** [comment]
Hi guys, I talked to @guns2410 and he gave me access to maintain this repository. Nevertheless, I don't have access to NPM to publish a new version, so I just made a commit with the build folders in order to make possible installing this library from git.
